back_end/intern/first_app/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
# Template URL's
app_name = 'first_app'

urlpatterns = [

    path('',views.home, name = 'home'),
    path('about/',views.about, name = 'about'),
    path('blog/', views.blog, name = 'blog'),
    path('contactUs/',views.contactUs, name ='contactus'),
    path('index/',views.index, name ='index'),
    path('post_1/', views.post_1, name = 'post_1'),
    path('post_2/', views.post_2, name = 'post_2'),
    path('post_3/', views.post_3, name = 'post_3'),
    path('post_4/', views.post_4, name = 'post_4'),
    path('post_5/', views.post_5, name = 'post_5'),
    path('cart/', views.cart, name = 'cart'),
    path('post/', views.post, name = 'post'),
    path('product/', views.product, name = 'product'),
    path('services/', views.services, name = 'services'),
    path('register/',views.user_signup, name = 'user_signup'),
    path('login/',views.user_login, name = 'user_login')
    

]
#need to add after running server
#path('login/', views.login, name = 'login'),

back_end/intern/intern/urls.py
from django.contrib import admin
from django.urls import path,include
from first_app import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name = 'home'),
    path('first_app/',include('first_app.urls')),
    path('logout/', views.logout, name = 'logout'),
    path('special/',views.special, name = 'special')
]

back_end/intern/first_app/models.py
from django.db import models
from django.contrib.auth.models import User
# # from django.contrib.auth.models import User

# # # Create your models here.
# # class UserProfileInfo(models.Model):

# #     # create relationship (don't inherit from User!)
# #     user = models.OneToField(User)
# #     # add any additional attributes you want 

# #     def __self__(self):
# #         return self.user.username
# class Topic(models.Model):
#     top_name = models.charField(max_length = 264, unique = True)
#     number = models.IntegerField()
#     email = models.EmailField()
#     text = models.

class Post(models.Model):
    user = models.OneToOneField(User,on_delete = models.CASCADE, primary_key = True)
    #additional attributes
    name = models.CharField(max_length=300, unique= True,default = 'name')
    number = models.CharField(max_length = 300, unique= True, default = '9999999999')
    comments = models.CharField(max_length=300, default = "Enter comments")
    def __str__(self):
        return self.user.name


class FormSl(models.Model):
    # for signup and login
    first_name = models.CharField(max_length= 32, unique = True)
    last_name = models.CharField(max_length= 32, unique = True)
    emailid = models.EmailField()
    number = models.IntegerField()
    up = models.CharField(max_length = 32, unique = True)
    up2 = models.CharField(max_length = 32, unique = True)

class LoginMod(models.Model):
    email = models.EmailField()
    password = models.CharField(max_length = 32)


# class UserProfileInfo(models.Model):
#     user = models.CharField(max_length = 300, unique = True)
    
#     def __str__(self):
#         return self.user.username

back_end/intern/first_app/forms.py
from django import forms
from django.forms import Textarea
from django.contrib.auth.models import User
from first_app.models import Post,FormSl


class FormName(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    number = forms.IntegerField()
    text = forms.CharField(widget = forms.Textarea)
class FormN(forms.Form):
    
    class Meta:
        model = Post
        fields = ('name','email','number','comments')
        widgets = {'comments' : Textarea(attrs = {'rows': 7, 'cols': 40})}
class SignupForm(forms.ModelForm):
    class Meta:
        model = FormSl
        fields = '__all__'
        widgets = {
            'up' : forms.PasswordInput(),
            'up2' : forms.PasswordInput()
        }

class LoginForm(forms.Form):
    class Meta:
        model = LoginMod
        fields = '__all__'
        widgets = {
            'password' : forms.PasswordInput()
        }
    
        
      

back_end/intern/first_app/views.py
from django.shortcuts import render
#from first_app.models import NewUserForm 
from first_app.forms import FormN,SignupForm,LoginForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate,login,logout
# formname for contact us

# Create your views here.
def home(request):
    return render(request,'first_app/Home.html')
def about(request):
    return render(request,'first_app/About.html')
# def buynow(request):
#     return render(request, 'first_app/Buynow.html')
def cart(request):
    return render(request, 'first_app/cart.html')

def blog(request):
    return render(request,'first_app/blog.html')
def contactUs(request):
    form = FormN()
    if request.method == 'POST':
        form = FormN(request.POST)
        if form.is_valid():
            form.save(commit = True)
            return home(request)
        else:
            print("Fill out Form correctly!")
    return render(request, 'first_app/contactUs.html', {'form': form})
def index(request):
    return render(request,'first_app/index.html')

def post_1(request):
    return render(request, 'first_app/post-1.html')

def post_2(request):
    return render(request, 'first_app/post-2.html')

def post_3(request):
    return render(request, 'first_app/post-3.html')

def post_4(request):
    return render(request, 'first_app/post-4.html')

def post_5(request):
    return render(request, 'first_app/post-5.html')

def post(request):
    return render(request, 'first_app/post.html')

def product(request):
    return render(request, 'first_app/Product.html')

def services(request):
    return render(request, 'first_app/services.html')

def cart(request):
    return render(request, 'first_app/cart.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))

@login_required
def special(request):
    return HttpResponse("You are logged in")

# def login(request):
#     pass
#     # form = Login()
#     # if request.method == 'POST':
#     #     form = Login(request.POST)
#     #     if form.is_valid():
#     #         form.save(commit = True)
#     #         return home(request)
#     #     else:
#     #         return "Form is invalid"

def user_login(self, request):
    
    if request.method=='POST':
        register_status = False
        if request.POST.get('submit') == 'checkform1':
            user_form = SignupForm(data = request.POST)
            if user_form.is_valid():
                user = user_form.save()
                user.set_password(user.up)
                user.save()
                register_status = True
            else:
                print(user_form.errors)
        else:
            user_form = SignupForm()
        return render(request, 'first_app/Login.html', {'user_form':user_form,'register_status': register_status})
    elif request.POST.get('submit') == 'checkform2':
        pass

        ## do what ever you want to do for first function ####
    
            ## do what ever you want to do for second function ####
        ## return def post###  
    return render(request, 'first_app/Login.html', {'user_form':user_form,})

back_end/intern/templates/first_app/Login.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>login/signup</title>
        <link rel="stylesheet" href="{% static 'css/style1.css' %}">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    </head>
    <body>

        {% if register_status %}
            <h1>Thank you for registering</h1>
        {% else %}
        <div id='login-form' class='login-page'>
            <div class="form-box">
                <div class='button-box'>
                    <div id='btn'></div>
                    <button type='button' onclick='register()' class='toggle-btn'> Signup </button>
                    <button type='button' onclick='login()' class='toggle-btn' > Login </button>
                </div>

                <form method = "POST" enctype="multipart/form-data" id="register" class="input-group-register needs-validation" novalidate oninput='up2.setCustomValidity(up2.value != up.value ? "Passwords do not match." : "")'> 
                    {{ user_form.as_p }}
                    {% csrf_token %}
                    
                    <input type="text" class="input-field" id="firstname" placeholder="First Name" name = "first_name" required>
                    <div class="invalid-feedback">Please enter a valid first name.</div>
                    <input type="text" class="input-field" id="lastname" name = "last_name" placeholder="Last Name" required>
                    <div class="invalid-feedback">Please enter a valid last name.</div>
                    <input type="email" class="input-field" id="email" name = "emailid" placeholder="Email" required>
                    <div class="invalid-feedback">Please enter a valid Email Address.</div>
                    <input type="number" class="input-field" id="mobile" name = "number" placeholder="Mobile" required>
                    <div class="invalid-feedback">Please enter your Mobile Number.</div>
                    <input type="password" class="input-field" id="password" placeholder="Enter Password" name="up" required>
                    <div class="invalid-feedback">Please enter your password.</div>
                    <input type="password" class="input-field" id="confirmpassword" placeholder="Confirm Password" name="up2" required>
                    <div class="invalid-feedback">Password doesn't match.</div>
                    <input type="checkbox" class="check-box" required> <span> I agree to the Terms & Conditions </span>
                    <div class="invalid-feedback">You must agree before submitting.</div>
                    <button type="submit" name = "submit" class="submit-btn" value="checkform1"> SignUp </button>
                </form>


                <form action = "{% url 'first_app:user_login'%}" method = "POST" enctype="multipart/form-data" id="login" class="input-group-login needs-validation" novalidate>
                    {% csrf_token %}
                    {{ login_user.as_p }}

                    <input type="email" name = "email" class="input-field" id="email" placeholder="Email" required>
                    <div class="invalid-feedback"> Please enter a valid email address.</div>
                    <input type="password" class="input-field" name = "password" id="password" placeholder="Password" required>
                    <div class="invalid-feedback"> Please enter password </div>
                    <input type="checkbox" class="check-box"> <span> Remember Me ! </span>
                    <button type="submit" name = 'submit' class="submit-btn" value="checkform2"> Login </button>
                </form>   
                
            </div>
        </div>            

        <script> 
            var x=document.getElementById('login');
            var z=document.getElementById('btn');
            // function register(){
            //     x.style.left = '-400px';
            //     y.style.left = '50px';
            //     z.style.left = '110px';
            // }
            function login(){
                x.style.left = '50px';
                y.style.left = '-400px';
                z.style.left = '0px';
            }
        </script> 


        

back_end/intern/templates/first_app/cart.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class = "container">
        <div class = "jumbotron"> 
            <h1 style = "background-color: lightsalmon;color:mediumslateblue;text-align: center;">Currently you have no items in the cart</h1>
            <img src="{% static 'images/oops.jpg' %}" alt="" style = "width: 450px; height: 400px;  display: block;margin-left: auto;margin-right: auto;width: 50%;">
        </div>
        
    </div>
    
    
</body>
</html>

back_end/intern/templates/first_app/post-1.html
<!doctype html>
{% load static %}
<html style="font-size: 16px;"><head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="Post 1 Headline">
    <meta name="description" content="">
    <meta name="page_type" content="np-template-header-footer-from-plugin">
    <title>Post 2 Headline</title>
    <link rel="stylesheet" href="{% static 'css/nicepage.css' %}" media="screen">
<link rel="stylesheet" href="{% static 'css/Post-Template.css' %}" media="screen">
    <script class="u-script" type="text/javascript" src="{% static 'javascript/jquery.js' %}" defer=""></script>
    <script class="u-script" type="text/javascript" src="[% static 'javascript/nicepage.js' %}" defer=""></script>
    <meta name="generator" content="Nicepage 3.6.6, nicepage.com">
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i">
    <link id="u-page-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Almendra:400,400i,700,700i">
    
    
    <script type="application/ld+json">{
		"@context": "http://schema.org",
		"@type": "Organization",
		"name": "",
		"url": "{% static 'index.html' %}",
		"logo": "{% static 'images/ce6ee4ef6336694ac0eff7e740c8528344ee5b30edfbf559e005450fc078647b7ac35e8e326029e91b8d1cfd51ed53ef0bc3d8e77e30ff0ad94533_1280.jpg' %}",
		"sameAs": []
}</script>
    <meta property="og:title" content="Post Template">
    <meta property="og:type" content="website">
    <meta name="theme-color" content="#478ac9">
    <link rel="canonical" href="{% static 'index.html' %}">
    <meta property="og:url" content="{% static 'index.html' %}">
  </head>
  <body class="u-body"><header class="u-clearfix u-header u-header" id="sec-accd"><div class="u-clearfix u-sheet u-sheet-1">
        <a href="{% url 'first_app:home' %}" data-page-id="239802916" class="u-image u-logo u-image-1" title="Home" data-image-width="1280" data-image-height="853">
          <img src="{% static 'images/ce6ee4ef6336694ac0eff7e740c8528344ee5b30edfbf559e005450fc078647b7ac35e8e326029e91b8d1cfd51ed53ef0bc3d8e77e30ff0ad94533_1280.jpg' %}" class="u-logo-image u-logo-image-1" data-image-width="64">
        </a>
        <nav class="u-align-right u-menu u-menu-dropdown u-offcanvas u-menu-1">
          <div class="menu-collapse" style="font-size: 1rem; letter-spacing: 0px; font-weight: 700; text-transform: uppercase;">
            <a class="u-button-style u-custom-active-border-color u-custom-active-color u-custom-border u-custom-border-color u-custom-borders u-custom-hover-border-color u-custom-hover-color u-custom-left-right-menu-spacing u-custom-padding-bottom u-custom-text-active-color u-custom-text-color u-custom-text-hover-color u-custom-top-bottom-menu-spacing u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="#">
              <svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#menu-hamburger"></use></svg>
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs><symbol id="menu-hamburger" viewBox="0 0 16 16" style="width: 16px; height: 16px;"><rect y="1" width="16" height="2"></rect><rect y="7" width="16" height="2"></rect><rect y="13" width="16" height="2"></rect>
</symbol>
</defs></svg>
            </a>
          </div>
          <div class="u-custom-menu u-nav-container">
            <ul class="u-nav u-spacing-30 u-unstyled u-nav-1"><li class="u-nav-item"><a class="u-border-2 u-border-active-palette-1-base u-border-hover-palette-1-light-1 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-grey-90 u-text-grey-90 u-text-hover-grey-90" href="{% url 'first_app:home' %}" style="padding: 10px 0px;">Home</a>
</li><li class="u-nav-item"><a class="u-border-2 u-border-active-palette-1-base u-border-hover-palette-1-light-1 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-grey-90 u-text-grey-90 u-text-hover-grey-90" href="{% url 'first_app:about' %}" style="padding: 10px 0px;">About</a>
</li><li class="u-nav-item"><a class="u-border-2 u-border-active-palette-1-base u-border-hover-palette-1-light-1 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-grey-90 u-text-grey-90 u-text-hover-grey-90" href= "" style="padding: 10px 0px;">Buy Now</a>
</li><li class="u-nav-item"><a class="u-border-2 u-border-active-palette-1-base u-border-hover-palette-1-light-1 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-grey-90 u-text-grey-90 u-text-hover-grey-90" href = "{% url 'first_app:cart' %}" style="padding: 10px 0px;">Cart</a>
</li><li class="u-nav-item"><a class="u-border-2 u-border-active-palette-1-base u-border-hover-palette-1-light-1 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-grey-90 u-text-grey-90 u-text-hover-grey-90" href="{% url 'first_app/Contact-Us.html' %}" style="padding: 10px 0px;">Contact Us</a>
</li><li class="u-nav-item"><a class="u-border-2 u-border-active-palette-1-base u-border-hover-palette-1-light-1 u-border-no-left u-border-no-right u-border-no-top u-button-style u-nav-link u-text-active-grey-90 u-text-grey-90 u-text-hover-grey-90" style="padding: 10px 0px;">Services</a>
</li></ul>
          </div>
          <div class="u-custom-menu u-nav-container-collapse">
            <div class="u-black u-container-style u-inner-container-layout u-opacity u-opacity-85 u-sidenav">
              <div class="u-sidenav-overflow">
                <div class="u-menu-close"></div>
                <ul class="u-align-center u-nav u-popupmenu-items u-spacing-13 u-unstyled u-nav-2"><li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% static 'first_app/Home.html' % }" style="padding: 10px 0px;">Home</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% static 'first_app/About.html' % }" style="padding: 10px 0px;">About</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link" style="padding: 10px 0px;">Buy Now</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link" style="padding: 10px 0px;">Cart</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% static 'first_app/Contact-Us.html' %}" style="padding: 10px 0px;">Contact Us</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link" style="padding: 10px 0px;">Services</a>
</li></ul>
              </div>
            </div>
            <div class="u-black u-menu-overlay u-opacity u-opacity-45"></div>
          </div>
        </nav>
        <h2 class="u-custom-font u-text u-text-1">Techpark Innovation</h2>
      </div></header>
    <section class="u-align-center u-clearfix u-section-1" id="sec-05a9">
      <div class="u-clearfix u-sheet u-valign-middle-md u-valign-middle-sm u-valign-middle-xs u-sheet-1"><!--post_details--><!--post_details_options_json--><!--{"source":""}--><!--/post_details_options_json--><!--blog_post-->
        <div class="u-container-style u-expanded-width u-post-details u-post-details-1">
          <div class="u-container-layout u-valign-middle u-container-layout-1"><!--blog_post_image-->
            <img alt="" class="u-blog-control u-expanded-width u-image u-image-default u-image-1" src="{% static 'images/images/2.jpeg' %}"><!--/blog_post_image--><!--blog_post_header-->
            <h2 class="u-blog-control u-text u-text-1">Post 2 Headline</h2><!--/blog_post_header--><!--blog_post_metadata-->
            <div class="u-blog-control u-metadata u-metadata-1"><!--blog_post_metadata_date-->
              <span class="u-meta-date u-meta-icon">Feb 24, 2021</span><!--/blog_post_metadata_date--><!--blog_post_metadata_category-->
              <!--/blog_post_metadata_category--><!--blog_post_metadata_comments-->
              <!--/blog_post_metadata_comments-->
            </div><!--/blog_post_metadata--><!--blog_post_content-->
            <div class="u-align-justify u-blog-control u-post-content u-text u-text-2 fr-view">
  Sample small text. Lorem ipsum dolor sit amet.
  </div><!--/blog_post_content-->
          </div>
        </div><!--/blog_post--><!--/post_details-->
      </div>
    </section>
    
    
    <footer class="u-clearfix u-footer u-grey-80" id="sec-31b3"><div class="u-clearfix u-sheet u-sheet-1">
        <div class="u-align-left u-social-icons u-spacing-10 u-social-icons-1">
          <a class="u-social-url" title="facebook" target="_blank" href=""><span class="u-icon u-icon-circle u-social-facebook u-social-icon u-icon-1"><svg class="u-svg-link" preserveAspectRatio="xMidYMin slice" viewBox="0 0 112 112" style=""><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-21d5"></use></svg><svg class="u-svg-content" id="svg-21d5" style="color: rgb(59, 89, 152);"><circle fill="currentColor" cx="56.1" cy="56.1" r="55"></circle><path fill="#FFFFFF" d="M73.5,31.6h-9.1c-1.4,0-3.6,0.8-3.6,3.9v8.5h12.6L72,58.3H60.8v40.8H43.9V58.3h-8V43.9h8v-9.2
            c0-6.7,3.1-17,17-17h12.5v13.9H73.5z"></path></svg></span>
          </a>
          <a class="u-social-url" title="twitter" target="_blank" href=""><span class="u-icon u-icon-circle u-social-icon u-social-twitter u-icon-2"><svg class="u-svg-link" preserveAspectRatio="xMidYMin slice" viewBox="0 0 112 112" style=""><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-16c1"></use></svg><svg class="u-svg-content" id="svg-16c1" style="color: rgb(85, 172, 238);"><circle fill="currentColor" class="st0" cx="56.1" cy="56.1" r="55"></circle><path fill="#FFFFFF" d="M83.8,47.3c0,0.6,0,1.2,0,1.7c0,17.7-13.5,38.2-38.2,38.2C38,87.2,31,85,25,81.2c1,0.1,2.1,0.2,3.2,0.2
            c6.3,0,12.1-2.1,16.7-5.7c-5.9-0.1-10.8-4-12.5-9.3c0.8,0.2,1.7,0.2,2.5,0.2c1.2,0,2.4-0.2,3.5-0.5c-6.1-1.2-10.8-6.7-10.8-13.1
            c0-0.1,0-0.1,0-0.2c1.8,1,3.9,1.6,6.1,1.7c-3.6-2.4-6-6.5-6-11.2c0-2.5,0.7-4.8,1.8-6.7c6.6,8.1,16.5,13.5,27.6,14
            c-0.2-1-0.3-2-0.3-3.1c0-7.4,6-13.4,13.4-13.4c3.9,0,7.3,1.6,9.8,4.2c3.1-0.6,5.9-1.7,8.5-3.3c-1,3.1-3.1,5.8-5.9,7.4
            c2.7-0.3,5.3-1,7.7-2.1C88.7,43,86.4,45.4,83.8,47.3z"></path></svg></span>
          </a>
          <a class="u-social-url" title="instagram" target="_blank" href=""><span class="u-icon u-icon-circle u-social-icon u-social-instagram u-icon-3"><svg class="u-svg-link" preserveAspectRatio="xMidYMin slice" viewBox="0 0 112 112" style=""><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-928f"></use></svg><svg class="u-svg-content" id="svg-928f" style="color: rgb(197, 54, 164);"><circle fill="currentColor" cx="56.1" cy="56.1" r="55"></circle><path fill="#FFFFFF" d="M55.9,38.2c-9.9,0-17.9,8-17.9,17.9C38,66,46,74,55.9,74c9.9,0,17.9-8,17.9-17.9C73.8,46.2,65.8,38.2,55.9,38.2
            z M55.9,66.4c-5.7,0-10.3-4.6-10.3-10.3c-0.1-5.7,4.6-10.3,10.3-10.3c5.7,0,10.3,4.6,10.3,10.3C66.2,61.8,61.6,66.4,55.9,66.4z"></path><path fill="#FFFFFF" d="M74.3,33.5c-2.3,0-4.2,1.9-4.2,4.2s1.9,4.2,4.2,4.2s4.2-1.9,4.2-4.2S76.6,33.5,74.3,33.5z"></path><path fill="#FFFFFF" d="M73.1,21.3H38.6c-9.7,0-17.5,7.9-17.5,17.5v34.5c0,9.7,7.9,17.6,17.5,17.6h34.5c9.7,0,17.5-7.9,17.5-17.5V38.8
            C90.6,29.1,82.7,21.3,73.1,21.3z M83,73.3c0,5.5-4.5,9.9-9.9,9.9H38.6c-5.5,0-9.9-4.5-9.9-9.9V38.8c0-5.5,4.5-9.9,9.9-9.9h34.5
            c5.5,0,9.9,4.5,9.9,9.9V73.3z"></path></svg></span>
          </a>
          <a class="u-social-url" title="linkedin" target="_blank" href=""><span class="u-icon u-icon-circle u-social-icon u-social-linkedin u-icon-4"><svg class="u-svg-link" preserveAspectRatio="xMidYMin slice" viewBox="0 0 112 112" style=""><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-6f15"></use></svg><svg class="u-svg-content" id="svg-6f15" style="color: rgb(0, 122, 185);"><circle fill="currentColor" cx="56.1" cy="56.1" r="55"></circle><path fill="#FFFFFF" d="M41.3,83.7H27.9V43.4h13.4V83.7z M34.6,37.9L34.6,37.9c-4.6,0-7.5-3.1-7.5-7c0-4,3-7,7.6-7s7.4,3,7.5,7
            C42.2,34.8,39.2,37.9,34.6,37.9z M89.6,83.7H76.2V62.2c0-5.4-1.9-9.1-6.8-9.1c-3.7,0-5.9,2.5-6.9,4.9c-0.4,0.9-0.4,2.1-0.4,3.3v22.5
            H48.7c0,0,0.2-36.5,0-40.3h13.4v5.7c1.8-2.7,5-6.7,12.1-6.7c8.8,0,15.4,5.8,15.4,18.1V83.7z"></path></svg></span>
          </a>
        </div>
      </div></footer>
    <section class="u-backlink u-clearfix u-grey-80">
      <a class="u-link" href="https://nicepage.com/website-templates" target="_blank">
        <span>Website Templates</span>
      </a>
      <p class="u-text">
        <span>created with</span>
      </p>
      <a class="u-link" href="https://nicepage.com/" target="_blank">
        <span>Website Builder Software</span>
      </a>. 
    </section>
  
</body></html>